sudo: required
services:
    - docker
before_install:
    - docker build -t mikeadkins/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run mikeadkins/react-test npm test -- --watchAll=false

after_success:
    - docker build -t madkins2121/multi-client ./client
    - docker build -t madkins2121/multi-nginx ./nginx
    - docker build -t madkins2121/multi-server ./server
    - docker build -t madkins2121/multi-worker ./worker
    # Log into the docker cli
    - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_ID' --password-stdin
    # Take those images and push them to docker hub
    - docker push madkins2121/multi-client:latest
    - docker push madkins2121/multi-nginx:latest
    - docker push madkins2121/multi-server:latest
    - docker push madkins2121/multi-worker:latest
    
